version: '3.7'

services:
  dash_app:
    build:
      context: .
      dockerfile: ./dockerfiles/dash_app/Dockerfile  # Specify the path to your Dockerfile
    ports:
      - "8050:8050"  # Map the container's port to the host machine's port
    environment:
      - API_SERVER_HOST=app
      - API_SERVER_PORT=8000
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Dockerfile
    ports:
      - "8000:8000"  # Map the container's port to the host machine's port
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # Map the container's port to the host machine's port
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

